
// Pipeline Runner — orchestrates task execution through stages
// Usage: load in node_repl, then run: runPipeline('production-4', tasks)

var pipelineConfig = JSON.parse(require('fs').readFileSync(__dirname + '/config.json', 'utf8'));

function runPipeline(pipelineName, taskList) {
  var pipeline = pipelineConfig.stages[pipelineName];
  if (!pipeline) return { error: 'Pipeline not found: ' + pipelineName };
  
  var results = [];
  var taskOutputs = {};
  
  console.log('\n========================================');
  console.log('Pipeline: ' + pipeline.name);
  console.log('Tasks: ' + (taskList.tasks || taskList).length);
  console.log('========================================\n');
  
  var tasks = taskList.tasks || taskList;
  
  for (var i = 0; i < tasks.length; i++) {
    var task = tasks[i];
    console.log('--- Task ' + (i+1) + '/' + tasks.length + ': ' + (task.product || task.id) + ' ---');
    
    var taskContext = { task: task, outputs: {}, store_url: taskList.store_url };
    
    for (var j = 0; j < pipeline.steps.length; j++) {
      var step = pipeline.steps[j];
      var execCtx = executeStage(step, taskContext);
      
      if (execCtx.error) {
        console.log('  [' + step.id + '] SKIP: ' + execCtx.error);
        continue;
      }
      
      console.log('  [' + step.id + '] Phase ' + (step.phase || '?') + ' | ' + step.skill);
      console.log('    Input: ' + execCtx.input.substring(0, 80) + (execCtx.input.length > 80 ? '...' : ''));
      
      // Store placeholder for downstream steps
      taskContext.outputs[step.output_key] = '[To be generated by ' + step.skill + ']';
      
      results.push({
        task_id: task.id,
        step_id: step.id,
        pipeline: pipelineName,
        execution_context: execCtx
      });
    }
    
    console.log('');
  }
  
  console.log('Pipeline complete: ' + results.length + ' execution contexts generated');
  
  return {
    pipeline: pipelineName,
    tasks_processed: tasks.length,
    steps_executed: results.length,
    execution_plan: results
  };
}

// Convenience: run all 3 pipelines for a task list
function runAllPipelines(taskList) {
  var allResults = {};
  var pipelines = ['production-4', 'review-6', 'operations-3'];
  
  for (var p of pipelines) {
    console.log('\n========== ' + p + ' ==========');
    allResults[p] = runPipeline(p, taskList);
  }
  
  // Generate final report
  var report = generateReport(allResults, taskList);
  allResults['_final_report'] = report;
  
  return allResults;
}

function generateReport(allResults, taskList) {
  var totalTasks = (taskList.tasks || taskList).length;
  var totalSteps = 0;
  for (var key in allResults) {
    if (key.startsWith('_')) continue;
    totalSteps += allResults[key].steps_executed;
  }
  
  return {
    title: 'Pipeline Execution Report',
    date: new Date().toISOString(),
    tasks: totalTasks,
    total_steps: totalSteps,
    pipelines: Object.keys(allResults).filter(k => !k.startsWith('_')),
    status: 'All execution contexts generated. Feed each context to the AI agent for actual execution.'
  };
}

console.log('Pipeline Runner loaded');
console.log('  runPipeline(pipelineName, taskList) — run one pipeline');
console.log('  runAllPipelines(taskList) — run all 3 pipelines');
console.log('  Pipelines: production-4, review-6, operations-3');
